name 'yacs'
maintainer 'Chef Customer Success Engineering Team'
maintainer_email 'success@chef.io'
license 'apache'
description 'Proof of Concept for deployment model'
long_description 'Proof of Concept for deployment model'
version '0.3.0'

depends 'chef-ingredient'
depends 'packagecloud'
